version: '3'
services:
  rualone-mysql:
    container_name: rualone-mysql # 컨테이너 이름 설정
    image: mysql:8.0 # 사용할 이미지
    restart: always
    ports:
      - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
    environment: # -e 옵션
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # MYSQL 패스워드 설정 옵션

    networks:
      - rualone
    #volumes:
      #- /Users/Shared/data/mysql-test:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)

  rualone-backend:
    container_name: rualone-backend
    image: ${SPRING_BOOT_IMAGE}
    ports:
      - "8080:8080"
    depends_on:
      - rualone-mysql
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

    environment:
      SPRING.DATASOURCE.URL: jdbc:mysql://rualone-mysql:3306/rualone?useSSL=false&allowPublicKeyRetrieval=true
      # volumes:   프론트랑 합친 후에 볼륨 설정 예정
    networks:
      - rualone

networks:
  rualone:
    driver: bridge
