version: '3'
services:
  mysql:
    image: mysql:8.0 # 사용할 이미지
    restart: always
    container_name: mysql # 컨테이너 이름 설정
    ports:
      - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
    environment: # -e 옵션
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # MYSQL 패스워드 설정 옵션
    #volumes:
      #- /Users/Shared/data/mysql-test:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)

  backend:
    container_name: rualone-backend
    image: kimich1218/rualone-backend:latest

    ports:
      - "8080:8080"
    depends_on:
      - mysql
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

    environment:
      SPRING.DATASOURCE.URL: jdbc:mysql://mysql:3306/rualone?serverTimezone=Asia/Seoul
  #    volumes:   프론트랑 합친 후에 볼륨 설정 예정
