spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: MYSQL_URL=jdbc:mysql://localhost:3306/rualone?serverTimezone=Asia/Seoul
    username: root
    password: rualone!
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none